language: go
sudo: false
go:
  - 1.13
  - tip
before_install:
  - go get github.com/mattn/goveralls
install:
  - go get -d -t ./...
script:
  - go test ./...
  - $HOME/gopath/bin/goveralls -service=travis-ci
